### ISSUE TITLE
Update to Formspree endpoint creation

### ISSUE THREAD

**Issue by daviddarnes** [cfjedimaster/raymondcamden2020#6]
## Summary
Hey Raymond! I stumbled upon [your Formspree tutorial](https://www.raymondcamden.com/2016/01/22/dynamic-subjects-with-formspree) and found it to be very helpful for anyone else using Formspree for their website forms. I just wanted to let you know that Formspree now doesn't require exposing your email to create forms, if you sign up for a free account at formspree.io you can generate a custom endpoint and use that instead. There's more info here on the help docs: https://help.formspree.io/hc/en-us/articles/360056076314-Phasing-out-legacy-forms-email-URLs

If you need any help with updating this article let me know! Happy to send over a PR into the article itself 👍🏻

**Comment by cfjedimaster** [comment]
I don't typically update older blog entries as if I did, I'd have to update pretty much everything all the time. :) That being said, you could leave a comment on the entry?

**Comment by daviddarnes** [comment]
That seems fair @cfjedimaster, I'll make a comment on the original post. Thanks for the response 🙂
